# html lang
language:  
  - zh-CN
  - en

# main menu navigation
menu:
  首页: /
  关于: /about
  联系: /contact
  归档: /archives

# stylesheets loaded in the <head>
stylesheets:
  - /css/oasis.css

# scripts loaded in the end of the body
scripts:
  - /js/oasis.js
  - /js/copy.js
  - /js/anchor.js

logo:
  - ./asset/logo.JPG
